#####################################################################
# Codecov configuration.
#####################################################################
ignore:
    - "web/assets/.*"
    - "web/build/.*"
    - "web/static/.*"
    - "web/test/.*"
